config/routes.rb
Rails.application.routes.draw do
  
  namespace 'api' do
    namespace 'v1' do
      resources :crafts
    end
  end

  resources :crafts
  resources :locations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/craft.rb
class Craft < ApplicationRecord

  validates :name, presence: true
  validates :description, presence: true

end

app/models/location.rb
class Location < ApplicationRecord

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

end

app/controllers/api/v1/crafts_controller.rb
module Api
  module V1

    class CraftsController < ApplicationController
      protect_from_forgery with: :null_session

      def index
        @crafts = Craft.all
        render json: {status: "Success", message: "Loaded Crafts", data: @crafts}, status: :ok
      end

      def show
        @craft = Craft.find(params[:id])
        render json: {status: "Success", message: "Loaded Crafts", data: @craft}, status: :ok
      end

      def create
        @craft = Craft.new(craft_params)

        if @craft.save
          render json: {status: "Berhasil", message: "Craft Saved", data: @craft}, status: :ok
        else
          render json: {status: "Error", message: "Craft can't be saved", data: @craft.errors}, status: :unprocessable_entity
        end
      end

      def update
        @craft = Craft.find(params[:id])

        if @craft.update_attributes(craft_params)
          render json: {status: "Berhasil", message: "Craft Updated", data: @craft}, status: :ok
        else
          render json: {status: "Berhasil", message: "Craft can't be Updated", data: @craft.errors}, status: :unprocessable_entity
        end
      end

      def destroy
        @craft = Craft.find(params[:id])

        
      end

      private

      def craft_params
        params.permit(:name, :description)
      end
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/crafts_controller.rb
class CraftsController < ApplicationController
  before_action :set_craft, only: [:show, :edit, :update, :destroy]

  # GET /crafts
  # GET /crafts.json
  def index
    @crafts = Craft.all
  end

  # GET /crafts/1
  # GET /crafts/1.json
  def show
  end

  # GET /crafts/new
  def new
    @craft = Craft.new
  end

  # GET /crafts/1/edit
  def edit
  end

  # POST /crafts
  # POST /crafts.json
  def create
    @craft = Craft.new(craft_params)

    respond_to do |format|
      if @craft.save
        format.html { redirect_to @craft, notice: 'Craft was successfully created.' }
        format.json { render :show, status: :created, location: @craft }
      else
        format.html { render :new }
        format.json { render json: @craft.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crafts/1
  # PATCH/PUT /crafts/1.json
  def update
    respond_to do |format|
      if @craft.update(craft_params)
        format.html { redirect_to @craft, notice: 'Craft was successfully updated.' }
        format.json { render :show, status: :ok, location: @craft }
      else
        format.html { render :edit }
        format.json { render json: @craft.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crafts/1
  # DELETE /crafts/1.json
  def destroy
    @craft.destroy
    respond_to do |format|
      format.html { redirect_to crafts_url, notice: 'Craft was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_craft
      @craft = Craft.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def craft_params
      params.require(:craft).permit(:name, :description)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:address, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crafts_helper.rb
module CraftsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/crafts/_form.html.erb
<%= form_with(model: craft, local: true) do |form| %>
  <% if craft.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(craft.errors.count, "error") %> prohibited this craft from being saved:</h2>

      <ul>
      <% craft.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/crafts/edit.html.erb
<h1>Editing Craft</h1>

<%= render 'form', craft: @craft %>

<%= link_to 'Show', @craft %> |
<%= link_to 'Back', crafts_path %>

app/views/crafts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Crafts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crafts.each do |craft| %>
      <tr>
        <td><%= craft.name %></td>
        <td><%= craft.description %></td>
        <td><%= link_to 'Show', craft %></td>
        <td><%= link_to 'Edit', edit_craft_path(craft) %></td>
        <td><%= link_to 'Destroy', craft, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Craft', new_craft_path %>

app/views/crafts/new.html.erb
<h1>New Craft</h1>

<%= render 'form', craft: @craft %>

<%= link_to 'Back', crafts_path %>

app/views/crafts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @craft.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @craft.description %>
</p>

<%= link_to 'Edit', edit_craft_path(@craft) %> |
<%= link_to 'Back', crafts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prototype</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location, local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.address %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" 
%>

<h3>Nearby Location</h3>

<ul>
  <% for location in @location.nearbys(10) %>
    <li> <%= link_to location.address, location %> (<%= location.distance.round(2) %> miles )</li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

<!-- "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers" -->